name: Build release series tagged container images

on:
  push:
    branches:
      - software-5488-moving-dockerfiles
  pull_request:
  repository_dispatch:
    types:
      - dispatch-build
  workflow_dispatch:

jobs:
  make-date-tag:
    runs-on: ubuntu-latest
    outputs:
      dtag: ${{ steps.mkdatetag.outputs.dtag }}
    steps:
    - name: make date tag
      id: mkdatetag
      run: echo "::set-output name=dtag::$(date +%Y%m%d-%H%M)"

  build-images:
    name: compute-entrypoint:${{ matrix.osg_series }}-${{ matrix.repo }} image build
    runs-on: ubuntu-latest
    needs: [make-date-tag]
    strategy:
      fail-fast: False
      matrix:
        repo: ['development', 'testing', 'release']
        image: ['hosted-ce', 'osg-ce-condor']
        osg_series: ['3.6']
    steps:

    - uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Log in to OSG Harbor
      uses: docker/login-action@v1
      if: github.event_name != 'pull_request' && startsWith(github.repository, 'opensciencegrid/')
      with:
        registry: hub.opensciencegrid.org
        username: ${{ secrets.OSG_HARBOR_ROBOT_USER }}
        password: ${{ secrets.OSG_HARBOR_ROBOT_PASSWORD }}

    - name: Build Docker image
      uses: docker/build-push-action@v2.2.2
      with:
        build-args: |
          BASE_YUM_REPO=${{ matrix.repo }}
          BASE_OSG_SERIES=${{ matrix.osg_series }}
        context: ./base
        file: ./base/Dockerfile
        pull: True
        load: True
        tags: base:latest
        target: base
    
    - name: Generate tag list
      id: generate-tag-list
      env:
        REPO: ${{ matrix.repo }}
        IMAGE: ${{ matrix.image }}
        OSG_SERIES: ${{ matrix.osg_series }}
        TIMESTAMP: ${{ needs.make-date-tag.outputs.dtag }}
      run: |
        docker_repo=opensciencegrid/$IMAGE
        tag_list=()
        for registry in hub.opensciencegrid.org docker.io; do
          for image_tag in "$OSG_SERIES-$REPO" "$OSG_SERIES-$REPO-$TIMESTAMP"; do
            tag_list+=("$registry/$docker_repo":"$image_tag")
          done
        done
        # This causes the tag_list array to be comma-separated below,
        # which is required for build-push-action
        IFS=,
        echo "::set-output name=taglist::${tag_list[*]}"
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        driver: docker
    
    - name: Build and push Hosted-CE Docker image
      uses: docker/build-push-action@v2.2.2
      with:
        load: true
        push: ${{ github.event_name != 'pull_request' && startsWith(github.repository, 'opensciencegrid/') }}
        context: ./hosted-ce
        file: ./hosted-ce/Dockerfile
        build-args: |
          BASE_YUM_REPO=${{ matrix.repo }}
          BASE_OSG_SERIES=${{ matrix.osg_series }}
        tags: "${{ steps.generate-tag-list.outputs.taglist }}"
    
    - name: Build and push osg-ce-condor Docker image
      uses: docker/build-push-action@v2.2.2
      with:
        load: true
        push: ${{ github.event_name != 'pull_request' && startsWith(github.repository, 'opensciencegrid/') }}
        context: ./osg-ce-condor
        file: ./osg-ce-condor/Dockerfile
        build-args: |
          BASE_YUM_REPO=${{ matrix.repo }}
          BASE_OSG_SERIES=${{ matrix.osg_series }}
        tags: "${{ steps.generate-tag-list.outputs.taglist }}"
